name: weather_app_flutter
description: Simple Weather App - Flutter


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

